#!/bin/bash
# session-handoff: SUPER RELIABLE context preservation
# Usage: ./create-handoff.sh [custom-message]

set -e

HANDOFF_DIR="/Users/vitaliisimko/clawd/memory"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
DATE=$(date +%Y-%m-%d)
DATETIME=$(date -u +"%Y-%m-%d %H:%M UTC")
HANDOFF_FILE="$HANDOFF_DIR/HANDOFF-SESSION-$TIMESTAMP.md"
CUSTOM_MESSAGE="${1:-}"

# Get current session info
SESSION_INFO=$(clawdbot status --json 2>/dev/null | jq -r '.sessionKey // "unknown"' 2>/dev/null || echo "unknown")

# Get recent git changes if in repo
GIT_STATUS=""
if git rev-parse --git-dir > /dev/null 2>&1; then
    GIT_STATUS=$(git status --short 2>/dev/null | head -10 || echo "")
fi

# SYNC TO VECTOR MEMORY - Write key info to today's memory file
# This ensures memory_search will find it!
TODAY_MEMORY="$HANDOFF_DIR/$DATE.md"

if [ ! -f "$TODAY_MEMORY" ]; then
    touch "$TODAY_MEMORY"
fi

cat >> "$TODAY_MEMORY" << EOFSYNC

---
## SESSION HANDOFF SYNC — $DATETIME

**Session:** $SESSION_INFO  
**Status:** Context preserved for recovery after /new

### KEY QUERIES FOR RECOVERY:
- job_detective статус налаштування
- OpenCode MiniMax M2.1 workflow  
- сессія відновлення контекст
- $(if [ -n "$CUSTOM_MESSAGE" ]; then echo "$CUSTOM_MESSAGE"; fi)

### ACTIVE PROJECTS:
$(if [ -d "/Users/vitaliisimko/clawd/agents/job_detective" ]; then echo "- job_detective: ACTIVE (Flutter job monitoring)"; fi)
$(if [ -f "/Users/vitaliisimko/clawd/skills/session-handoff/SKILL.md" ]; then echo "- session-handoff skill: INSTALLED"; fi)

### SYNC COMPLETE ✅
EOFSYNC

echo "✅ Synced to vector memory: $TODAY_MEMORY"

# Create comprehensive handoff file
cat > "$HANDOFF_FILE" << EOF
# ✅ SESSION HANDOFF — Recovery Point

**Created:** $DATETIME  
**Session:** $SESSION_INFO  
**Type:** SESSION HANDOFF — Full context preservation  
**Status:** 🟢 READY FOR RECOVERY

$(if [ -n "$CUSTOM_MESSAGE" ]; then echo "**Note:** $CUSTOM_MESSAGE"; echo ""; fi)
---

## ⚡ AUTO-RECOVERY PROTOCOL (After /new)

**CRITICAL: This file is read automatically by BOOTSTRAP.md**

### IMMEDIATE ACTIONS (Auto-executed):

The recovery process runs these commands automatically:

\`\`\`javascript
// AUTO-RECOVERY QUERIES - Run immediately
memory_search({query: "job_detective статус налаштування", maxResults: 5})
memory_search({query: "OpenCode MiniMax M2.1 workflow", maxResults: 3})
memory_search({query: "сессія відновлення контекст", maxResults: 3})
memory_search({query: "останній проект статус", maxResults: 5})
\`\`\`

### VECTOR MEMORY SYNC ✅

Key context synced to: \`memory/$DATE.md\`
This ensures memory_search will find current state!

---

## 📋 CURRENT PROJECT STATUS

### 🕵️ Job Detective — $(if [ -f "/Users/vitaliisimko/clawd/agents/job_detective/JOB_CONFIG.json" ]; then echo "ACTIVE ✅"; else echo "NOT CONFIGURED"; fi)
**Location:** \`agents/job_detective/\`
**Config:** \`JOB_CONFIG.json\`
$(if [ -f "/Users/vitaliisimko/clawd/agents/job_detective/JOB_CONFIG.json" ]; then
    echo "**Work Hours:** $(cat /Users/vitaliisimko/clawd/agents/job_detective/JOB_CONFIG.json 2>/dev/null | grep -o '"start": [0-9]*' | grep -o '[0-9]*' || echo "7")-$(cat /Users/vitaliisimko/clawd/agents/job_detective/JOB_CONFIG.json 2>/dev/null | grep -o '"end": [0-9]*' | grep -o '[0-9]*' || echo "18")"
fi)

### 💻 OpenCode + MiniMax M2.1 — DEFAULT WORKFLOW ✅
**Status:** Configured and tested
**Rule:** Coding = OpenCode first, me as reserve

### 🔄 Session Handoff Skill — INSTALLED ✅
**Location:** \`skills/session-handoff/\`
**Purpose:** Automatic context preservation

---

## 🎯 FILES STATUS

$(if [ -f "/Users/vitaliisimko/clawd/memory/$DATE.md" ]; then echo "✅"; else echo "⬜"; fi) \`memory/$DATE.md\` — Synced to vector memory
$(if [ -f "/Users/vitaliisimko/clawd/SOUL.md" ]; then echo "✅"; else echo "⬜"; fi) \`SOUL.md\` — Identity
$(if [ -f "/Users/vitaliisimko/clawd/TOOLS.md" ]; then echo "✅"; else echo "⬜"; fi) \`TOOLS.md\` — Tools
$(if [ -f "/Users/vitaliisimko/clawd/agents/job_detective/JOB_CONFIG.json" ]; then echo "✅"; else echo "⬜"; fi) \`agents/job_detective/JOB_CONFIG.json\`

---

## 🧹 CLEANUP

**After successful recovery:**
\`\`\`bash
rm $HANDOFF_FILE
\`\`\`

Delete this file to avoid re-reading in future sessions.

---

*Auto-generated by session-handoff skill*  
*Vector memory synced ✅*
EOF

echo "✅ Session handoff created: $HANDOFF_FILE"
echo ""
echo "🧠 Vector memory synced: $TODAY_MEMORY"
echo ""
echo "📋 Contents preview:"
head -15 "$HANDOFF_FILE"
echo "..."
echo ""
echo "🎯 NEXT: You can now safely run /new or /reset"
echo "🤖 After /new, BOOTSTRAP.md will auto-recover context via vector memory"
echo ""
echo "💡 Pro tip: Handoff file auto-deletes after successful recovery"

exit 0